package com.mycompany.registroupc;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;


public class CrearIU extends javax.swing.JFrame {

    /**
     * Creates new form CrearIU
     */
    public CrearIU() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelBorder2 = new oooo.PanelBorder();
        Contraseña = new javax.swing.JTextField();
        panelBorder3 = new oooo.PanelBorder();
        Contraseña1 = new javax.swing.JTextField();
        panelBorder4 = new oooo.PanelBorder();
        panelBorder5 = new oooo.PanelBorder();
        Contraseña3 = new javax.swing.JTextField();
        conContraseña = new javax.swing.JTextField();
        panelBorder6 = new oooo.PanelBorder();
        panelBorder7 = new oooo.PanelBorder();
        Contraseña4 = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        panelBorder8 = new oooo.PanelBorder();
        panelBorder9 = new oooo.PanelBorder();
        Contraseña5 = new javax.swing.JTextField();
        btcNombre = new javax.swing.JTextField();
        panelBorder10 = new oooo.PanelBorder();
        panelBorder11 = new oooo.PanelBorder();
        Contraseña6 = new javax.swing.JTextField();
        btcTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Crear Cuenta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(114, 200, 148));
        jPanel1.setForeground(new java.awt.Color(60, 155, 97));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AcademyMaster Registration");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Completo");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmar Contraseña");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");

        jButton1.setBackground(new java.awt.Color(114, 200, 148));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Cuenta");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(114, 200, 148));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelBorder2.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder2.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña.setToolTipText("Contraseña");
        Contraseña.setBorder(null);
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        panelBorder2.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 34));

        panelBorder3.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder3.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña1.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña1.setToolTipText("Contraseña");
        Contraseña1.setBorder(null);
        Contraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña1ActionPerformed(evt);
            }
        });
        panelBorder3.add(Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 285, 34));

        panelBorder2.add(panelBorder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 40));

        panelBorder4.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder4.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder5.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder5.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña3.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña3.setToolTipText("Contraseña");
        Contraseña3.setBorder(null);
        Contraseña3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña3ActionPerformed(evt);
            }
        });
        panelBorder5.add(Contraseña3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 285, 34));

        panelBorder4.add(panelBorder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 40));

        conContraseña.setBackground(new java.awt.Color(217, 217, 217));
        conContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conContraseña.setBorder(null);
        conContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conContraseñaActionPerformed(evt);
            }
        });
        panelBorder4.add(conContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 34));

        panelBorder6.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder6.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder7.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder7.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña4.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña4.setToolTipText("Contraseña");
        Contraseña4.setBorder(null);
        Contraseña4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña4ActionPerformed(evt);
            }
        });
        panelBorder7.add(Contraseña4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 285, 34));

        panelBorder6.add(panelBorder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 40));

        username.setBackground(new java.awt.Color(217, 217, 217));
        username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        panelBorder6.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 34));

        panelBorder8.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder8.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder9.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder9.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña5.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña5.setToolTipText("Contraseña");
        Contraseña5.setBorder(null);
        Contraseña5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña5ActionPerformed(evt);
            }
        });
        panelBorder9.add(Contraseña5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 285, 34));

        panelBorder8.add(panelBorder9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 40));

        btcNombre.setBackground(new java.awt.Color(217, 217, 217));
        btcNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcNombre.setBorder(null);
        btcNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcNombreActionPerformed(evt);
            }
        });
        panelBorder8.add(btcNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 34));

        panelBorder10.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder10.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder11.setBackground(new java.awt.Color(217, 217, 217));
        panelBorder11.setForeground(new java.awt.Color(222, 241, 119));
        panelBorder11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contraseña6.setBackground(new java.awt.Color(217, 217, 217));
        Contraseña6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña6.setToolTipText("Contraseña");
        Contraseña6.setBorder(null);
        Contraseña6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contraseña6ActionPerformed(evt);
            }
        });
        panelBorder11.add(Contraseña6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 285, 34));

        panelBorder10.add(panelBorder11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 300, 40));

        btcTelefono.setBackground(new java.awt.Color(217, 217, 217));
        btcTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcTelefono.setBorder(null);
        btcTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcTelefonoActionPerformed(evt);
            }
        });
        panelBorder10.add(btcTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 34));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\jesus\\Downloads\\4K.Video.Downloader.4.24.2.5380 - XYZ\\ProyectoDep-main (2)\\ProyectoDep-main (2)\\ProyectoDep-main\\RegistroUPC\\src\\main\\java\\oooo\\image_2__1___1_-removebg-preview.png")); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jesus CH & William S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(panelBorder6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(panelBorder8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelBorder10, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcNombreActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        CrearIU CR = new CrearIU();
        CR.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3MouseClicked
      //guardado  
    private void guardarRegistro(String nombre, String usuario, String contraseña, String telefono) {
        if (verificarExistenciaUsuario(usuario)) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario ya está en uso. Inténtalo con otro.");
            return;
        }       
        try {
            FileWriter writer = new FileWriter("registros.txt", true);
            writer.write(nombre + "," + usuario + "," + contraseña + "," + telefono + System.lineSeparator());
            writer.close();
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al guardar el registro.");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nombre = btcNombre.getText();
        String usuario = username.getText();
        String contraseña = Contraseña.getText();
        String confirmarContraseña = conContraseña.getText();
        String telefono = btcTelefono.getText();

        if (btcNombre.getText().isEmpty() || username.getText().isEmpty() || Contraseña.getText().isEmpty()|| conContraseña.getText().isEmpty() || btcTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
        } else {

        if (!contraseña.equals(confirmarContraseña)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            return;
        }

            if (tieneNumeros(btcNombre.getText())) {
                JOptionPane.showMessageDialog(null, "El nombre no debe contener numeros");
                
            } else if (notieneNumeros(btcTelefono.getText())){
                JOptionPane.showMessageDialog(null, "El telefono no puede contener letras");
            }else {
            if (verificarExistenciaUsuario(usuario)) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario ya está en uso. Inténtalo con otro.");
            return;
            } else {
            guardarRegistro(nombre, usuario, contraseña, telefono);
            JOptionPane.showMessageDialog(null, "Registro exitoso. Ahora puedes iniciar sesión.");
            btcNombre.setText("");
            username.setText("");
            Contraseña.setText("");
            conContraseña.setText("");
            btcTelefono.setText("");
            }
          }
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private static boolean tieneNumeros(String cadena) {
        for (char c : cadena.toCharArray()) {
            if (Character.isDigit(c)) {
                return true;
            }
        }
        return false;
    }
    
        private static boolean notieneNumeros(String cadena) {
        for (char c : cadena.toCharArray()) {
            if (Character.isLetter(c)) {
                return true;
            }
        }
        return false;
    }

    private boolean verificarExistenciaUsuario(String usuario) {
    try {
        FileReader reader = new FileReader("registros.txt");
        BufferedReader bufferedReader = new BufferedReader(reader);

        String linea;
        while ((linea = bufferedReader.readLine()) != null) {
            String[] partes = linea.split(",");
            if (partes.length > 1 && partes[1].equals(usuario)) {
                bufferedReader.close();
                return true;
            }
        }

        bufferedReader.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    return false;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IU u = new IU();
        u.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
           
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void conContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conContraseñaActionPerformed

    private void btcTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcTelefonoActionPerformed

    private void Contraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña1ActionPerformed

    private void Contraseña3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña3ActionPerformed

    private void Contraseña4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña4ActionPerformed

    private void Contraseña5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña5ActionPerformed

    private void Contraseña6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contraseña6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contraseña6ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contraseña;
    private javax.swing.JTextField Contraseña1;
    private javax.swing.JTextField Contraseña3;
    private javax.swing.JTextField Contraseña4;
    private javax.swing.JTextField Contraseña5;
    private javax.swing.JTextField Contraseña6;
    private javax.swing.JTextField btcNombre;
    private javax.swing.JTextField btcTelefono;
    private javax.swing.JTextField conContraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private oooo.PanelBorder panelBorder10;
    private oooo.PanelBorder panelBorder11;
    private oooo.PanelBorder panelBorder2;
    private oooo.PanelBorder panelBorder3;
    private oooo.PanelBorder panelBorder4;
    private oooo.PanelBorder panelBorder5;
    private oooo.PanelBorder panelBorder6;
    private oooo.PanelBorder panelBorder7;
    private oooo.PanelBorder panelBorder8;
    private oooo.PanelBorder panelBorder9;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
